print("\nInsira Seu Nome: ")
nome = input()
print("\nInsira seu numero de matricula(8 Digitos):")
rgm = input()
print("\nInsira o seu numero de faltas:")
faltas = float(input())
if faltas < 15:
    print("\nInsira sua nota 1:")
    n1 = float(input())
    print("\nInsira sua nota 2:")
    n2 = float(input())
    print("\nInsira sua nota 3:")
    n3 = float(input())
    print("\nInsira sua nota 4:")
    n4 = float(input())
    media = (n1 + n2 + n3 + n4) / 4
    if media < 4:
        print("\nAluno: " + nome)
        print("Matricula Nº: " + rgm)
        print("\nNota Média Final: " + str(media))
        print("Status: Reprovado")
        print("\nBoa sorte ano que vem....")
        print("\n")
    else:
        if media >= 6:
                print("Aluno: " + nome)
                print("Matricula Nº: " + rgm)
                print("\nNota Média Final: " + str(media))
                print("\nStatus: Aprovado")
                print("\nBoas Férias!!!!!!!!!!!")
                print("\n")
        else:
            print("\nAluno: " + nome)
            print("Matricula Nº: " + rgm)
            print("\nSua media final foi: " + str(media))
            print("\nStatus: Prova Final.")
            print("\nInsira sua nota do exame final:")
            n5 = float(input())
            final = n5 / 2
            if final < 2:
                print("\n")
                print("\nNota da avaliação final: " + str(final))
                print("\nStatus: Reprovado na avaliação final")
                print("\nBoa sorte no ano que vem!!!!!")
                print("\n")
            else:
                print("\n")
                print("\nNota da avaliação final: " + str(final))
                print("\nStatus: Aprovado")
                print("\nBoas Férias!!!!!")
                print("\n")
else:
    print("\nAluno: " + nome)
    print("Matricula N.º: " + rgm)
    print("\nStatus: Reprovado pelo limite de faltas.")
    print("\nPara saber suas notas, insira sua Nota 1:")
    n1 = float(input())
    print("\nInsira sua nota 2:")
    n2 = float(input())
    print("\nInsira sua nota 3:")
    n3 = float(input())
    print("\nInsira sua nota 4:")
    n4 = float(input())
    media = (n1 + n2 + n3 + n4) / 4
    if media < 4:
        print("\nMédia final: " + str(media))
        print("\nStatus: Reprovado pelas faltas e pelas notas.")
        print("\nBoa sorte no ano que vem!!!!!")
        print("\n")
    else:
        print("\nMédia final: " + str(media))
        print("\nStatus: Reprovado pelas faltas e aprovado pelas notas.")
        print("\nBoa sorte no ano que vem!!!!!")
        print("\n")