print("\nInsira Seu Nome: ")
nome = input()
print("\nInsira seu rgm:")
rgm = input()
print("\nInsira o seu numero de faltas:")
faltas = float(input())
if faltas < 15:
    print("\nInsira sua nota 1")
    n1 = float(input())
    print("\nInsira sua nota 2")
    n2 = float(input())
    print("\nInsira sua nota 3")
    n3 = float(input())
    print("\nInsira sua nota 4")
    n4 = float(input())
    media = (n1 + n2 + n3 + n4) / 4
    if media < 4:
        print("Aluno: " + nome)
        print("RGM: " + rgm)
        print("\nNota Média Final: " + str(media))
        print("Status: Reprovado")
        print("\nBoa sorte ano que vem....")
        print("\n")
    else:
        if media >= 6:
                print("Aluno: " + nome)
                print("RGM: " + rgm)
                print("\nNota Média Final: " + str(media))
                print("Status: Aprovado")
                print("\nBoas Férias!!!!!!!!!!!")
                print("\n")
        else:
            print("\nSua media final foi: " + str(media))
            print("Status: Prova Final.")
            print("\nInsira sua nota do exame final:")
            n5 = float(input())
            final = n5 / 2
            if final < 2:
                print("\n")
                print("Aluno: " + nome)
                print("RGM: " + rgm)
                print("\nNota da avaliação final: " + str(final))
                print("Status: Reprovado na avaliação final")
                print("\nBoa sorte no ano que vem!!!!!")
                print("\n")
            else:
                print("\n")
                print("Aluno: " + nome)
                print("RGM: " + rgm)
                print("\nNota da avaliação final: " + str(final))
                print("Status: Aprovado")
                print("\nBoas Férias!!!!!")
                print("\n")
else:
    print("\nAluno: " + nome)
    print("RGM: " + rgm)
    print("Status: Reprovado pelo limite de faltas.")
    print("\nPara saber suas notas, insira sua Nota 1")
    n1 = float(input())
    print("\nInsira sua nota 2")
    n2 = float(input())
    print("\nInsira sua nota 3")
    n3 = float(input())
    print("\nInsira sua nota 4")
    n4 = float(input())
    media = (n1 + n2 + n3 + n4) / 4
    if media < 4:
        print("\nMédia final: " + str(media))
        print("Status: Reprovado pelas faltas e pelas notas.")
        print("\nBoa sorte no ano que vem!!!!!")
        print("\n")
    else:
        print("\nMédia final: " + str(media))
        print("Status: Reprovado pelas faltas e aprovado pelas notas.")
        print("\nBoa sorte no ano que vem!!!!!")
        print("\n")